### ISSUE TITLE
Prism 7.0

### ISSUE THREAD

**Issue by metscore** [brianlagunas/DynamicallyDiscover-LoadModules#2]
Hi Brian,

I know this is a bit old, but I'm writing an application using Prism 7 that uses your idea of dynamic loading of modules.
It works nice and it is probably my implementation that screws up the dynamic part somewhere. Anyway, I've been investing some time into finding the issue but have failed. I was hoping that you might give me a bump in the right direction.

I min my application (derived from PrismApplication)  I've implemented
IModuleCatalog CreateModuleCatalog() to create a module catalog that loads my modules. This all works great when the application is starting up, i.e. it looks in the catalog where I have my modules (currently only one) and loads it.
The module contains 5 views that all follow the pattern of resolving their ViewModels and the region managers to add themselves to the region, something like this:

```
public partial class ModuleNiDacProviderView : UserControl, IModule
    {
        public ModuleNiDacProviderView()
        {
            InitializeComponent();
        }

        public void OnInitialized(IContainerProvider containerProvider)
        {
            var vm = containerProvider.Resolve<IModuleNiDacProvider>();
            this.DataContext = vm;

            var regionManager = containerProvider.Resolve<IRegionManager>();
            var region = SyntropyApplicationDefinitions.SyntropyUserModuleRegion;
            regionManager.AddToRegion(region, this);
        }

        public void RegisterTypes(IContainerRegistry containerRegistry)
        {
            containerRegistry.RegisterSingleton<IModuleNiDacProvider, ModuleNiDacProviderViewModel>();
        }
    }
```

The prism region is defined in my main view such as 

```
<dxdo:DockLayoutManager Grid.Row="1" x:Name="SyntropyUserModuleRegionDockManager" FloatingMode="Desktop" ClosedPanelsBarVisibility="Auto" ClosedPanelsBarPosition="Right" ShowFloatWindowsInTaskbar="False">
            <dxdo:LayoutGroup Orientation="Horizontal">
                <dxdo:DocumentGroup prism:RegionManager.RegionName="{x:Static SyntDefines:SyntropyApplicationDefinitions.SyntropyUserModuleRegion}">
                </dxdo:DocumentGroup>
            </dxdo:LayoutGroup>
        </dxdo:DockLayoutManager>
```

(Sorry for my company using DevExpress and not Infragistics)

However, if the loading of the module is happening at a later stage (i.e. the user puts the module dll file in the module directory when the application is already up and running) the modules are loaded nicely but with the main problem that the region does not exist.

It is like the region manager is referenced from somewhere else and has no knowledge of any regions. 
However, as I said, it all works great if the module dll is loaded from the overridden function InitializeModules() where the base.InitializeModules() is called and the loading of the modules works fine, i.e. the region manager knows about the region.

By the few clues I've given above, do you have any idea what I'm doing wrong ?

Thanks a bunch for Prism by the way, I really like it !!

A big thank you in advance, 

King regards
Magnus

**Comment by metscore** [comment]
I upgraded the example to Prism 7.1 and obviously it runs nicely... 
Dohhh...I've really need to investigate my own problem more into depth because regions are working as expected...   👍  My app doesn't...  👎

**Comment by brianlagunas** [comment]
Glad you narrowed it down to your code :)

**Comment by metscore** [comment]
Hi Brian,

I have a comment or question depending on how you look at it...  :-)

The dynamic loading modules have been wokring fine for me (up until recently that is). 

My Prism end user application is loading IModules dll:s and they are depending on a a GAC:ed component. The GAC:ed component had a version upgrade recently, and a policy file to redirect to the new version.
However the dynamic loading fails after the upgrade since it seems to try to load the previous version. I have compile-time references to the previous version but the new version should be used during run-time. (Another application (a server) uses the policy idea and it works as anticipated, i.e. the policy file is respected and the new GAC:ed version is used)

After some debugging I realized that the method `GetModuleInfos` tries to resolve modules that have not been loaded. However it seems to fail to do so since it returns an IEnumerable and then that is returned using the line 
`return modules.ToArray();`
This line comes after the 
`AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve -= resolveEventHandler;`
and I assume that the execution of `ToArray()` is deferred to after the resolve event handler has been disconnected.


If I change the code to

```
ResolveEventHandler resolveEventHandler = delegate (object sender, ResolveEventArgs args) { return OnReflectionOnlyResolve(args, info); };
AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve += resolveEventHandler;
IEnumerable<ModuleInfo> modules = GetNotAllreadyLoadedModuleInfos(info, IModuleType);
var result = modules.ToArray();
AppDomain.CurrentDomain.ReflectionOnlyAssemblyResolve -= resolveEventHandler;
return result;

```
the resolve event handler seem to be used and the policy file is respected. The application seem to work fine.
(The only change is to move the `modules.ToArray()` when the resolve event handler is still active)

Am I going about this the wrong way or is this a change that might be worthwhile considering ?

King regards
Magnus

**Comment by brianlagunas** [comment]
Do whatever works for you. This post isn't meant to be the final solution, just a guide to help you get it working. I'm glad you got it working again.

**Comment by metscore** [comment]
Oh, I see. Thanks for your feedback !

Have a great day !
King regards
Magnus
